import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import DarkMode from '@/components/DarkMode'
import { ArrowRight, InstagramLogo, TwitterLogo, FigmaLogo, DribbbleLogo } from "phosphor-react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-zinc-100 dark:bg-zinc-900 h-screen w-screen flex flex-col items-center justify-center content-center text-zinc-900 dark:text-zinc-100'>
        <section className=' border-b border-zinc-600 p-10 flex flex-col items-center justify-center content-center'>
          <DarkMode />
          <div className='text-4xl font-bold mt-10'>
            Simple Darkmode
          </div>
          <div className=' space-x-1'>
            <span>
              <Link className='underline text-indigo-500' href={"https://www.npmjs.com/package/next-themes"}>
                Next.js
              </Link>
            </span>
            <span>-</span>
            <Link className='underline text-indigo-500' href={"https://www.npmjs.com/package/next-themes"}>
              Next themes
            </Link>
            <span>-</span>
            <Link className='underline text-indigo-500' href={"https://www.npmjs.com/package/next-themes"}>
              Tailwindcss
            </Link>
          </div>

          <button className='px-3 py-1 border border-zinc-400 rounded mt-4 space-x-1'>
            <span>Learn how to use </span>
            <span>
              <ArrowRight className="relative inline-flex w-4 h-4 self-center" color='currentcolor' weight="duotone" />
            </span>
          </button>
        </section>

        <section className='space-y-4 flex flex-col items-center justify-center content-center mt-6'>

          <div>
            <Link href={"https://burakerenoglu.com"} target={"_blank"}>
              burakerenoglu.com
            </Link>
          </div>

          <div className='flex flex-row space-x-6'>
            <Link target={"_blank"} href='https://www.instagram.com/burakereno/' >
              <InstagramLogo size={28} weight="regular" color="currentcolor" />
            </Link>
            <Link target={"_blank"} href='https://twitter.com/burakerenoglu' >
              <TwitterLogo size={28} weight="regular" color="currentcolor" />
            </Link>
            <Link target={"_blank"} href='https://dribbble.com/burakereno' >
              <DribbbleLogo size={28} weight="regular" color="currentcolor" />
            </Link>
            <Link target={"_blank"} href='https://www.figma.com/@burakereno' >
              <FigmaLogo size={28} weight="regular" color="currentcolor" />
            </Link>
          </div>

          <Link href={"https://www.buymeacoffee.com/burakereno"}>
            <div className="w-[153px] pt-10">
              <Image
                className=' '
                src="/bmc-button.png"
                alt=""
                width={484}
                height={484}
                quality={100}
                placeholder="blur"
                blurDataURL="/skeleton.png"
              />
            </div>
          </Link>
        </section>
      </main>
    </>
  )
}
